//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Tests.Linux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Security.Tests.Linux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;baseline_id&quot;: &quot;OMS.Linux.1&quot;,
        ///    &quot;base_orig_id&quot;: &quot;1&quot;,
        ///    &quot;setting_count&quot;: 80,
        ///    &quot;scan_time&quot;: &quot;2018-12-11T14:49:56.021370113Z&quot;,
        ///    &quot;error&quot;: &quot;&quot;,
        ///    &quot;results&quot;: [
        ///        {
        ///            &quot;msid&quot;: &quot;2.1&quot;,
        ///            &quot;result&quot;: &quot;PASS&quot;,
        ///            &quot;error_text&quot;: &quot;&quot;,
        ///            &quot;cceid&quot;: &quot;CCE-3522-0&quot;,
        ///            &quot;severity&quot;: &quot;Important&quot;,
        ///            &quot;description&quot;: &quot;The nodev option should be enabled for all removable media.&quot;,
        ///            &quot;ruleId&quot;: &quot;5c7537f2-b90b-44a4-89c9-4fca5fd79ef7&quot;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string baseline_output_nice {
            get {
                return ResourceManager.GetString("baseline_output_nice", resourceCulture);
            }
        }
    }
}
